spring:
  application:
    name: digital-library

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-quiet-brook-a1slwoj5-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_okdBagiPmE92

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

jwt:
  secret: yd1kpDPKxbt7DhPMGotQm1D2Qtul8Eb+hwSOD4Xw7NA=
  expiration: 3600000   # 1 hour in milliseconds

gemini:
  api-key: AIzaSyD255F0t7a9gdd957qVJFbME7uzHoEDHHI
  model: gemini-3-flash-preview
