spring:
  application:
    name: digital-library

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-quiet-brook-a1slwoj5-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_okdBagiPmE92

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

